export const STORE = {
  STORE_CREATION_PENDING: {
    id: 'STORE_CREATION',
    title: 'Creando tu tienda',
    message: 'Estamos verificando algunas cosas, aguántanos',
    autoClose: false,
    loading: true,
  },
  STORE_CREATION_SUCCESS: {
    id: 'STORE_CREATION',
    title: 'Tienda creada',
    message: 'Tu tienda está en proceso de validación, esto puede tardar máximo 24h, te vamos a enviar un email cuando el proceso haya terminado. Si ya pasó este tiempo, contáctanos.',
    loading: false,
    autoClose: false,
  },
  STORE_CREATION_FAILED: {
    id: 'STORE_CREATION',
    color: 'red',
    title: 'No pudimos crear tu tienda',
    message: 'Inténtalo más tarde y si el problema continúa, contáctanos.',
    autoClose: true,
    loading: false,
  },
  STORE_PENDING_VALIDATION: {
    id: '',
    title: 'En proceso de validación',
    message: 'Tu tienda está en proceso de validación, esto puede tardar máximo 24h, si ya pasó este tiempo, contáctanos.',
    autoClose: false,
    color: 'orange'
  },
  STORE_UPDATE_PENDING: {
    id: 'STORE_UPDATE',
    loading: true,
    title: 'Actualizando Información',
    message: 'Estamos procesando la actualización.',
    autoClose: false,
    withCloseButton: false
  },
  STORE_UPDATE_SUCCESS: {
    id: 'STORE_UPDATE',
    loading: false,
    title: 'Información Actualizada',
    message: 'Listo, la información de tu local fue actualizada con éxito.',
    autoClose: 3000,
  },
  STORE_UPDATE_FAILED: {
    id: 'STORE_UPDATE',
    loading: false,
    title: 'No pudimos actualizar la información',
    message: 'Inténtalo más tarde y si el problema continúa, contáctanos.',
    autoClose: false,
    color: 'red',
  },
  STORE_QR_GENERATION_PENDING: {
    id: 'STORE_QR_GENERATION',
    loading: true,
    title: 'Generando QR',
    message: 'Estamos procesando la solicitud',
    autoClose: false,
    withCloseButton: false
  },
  STORE_QR_GENERATION_SUCCESS: {
    id: 'STORE_QR_GENERATION',
    loading: false,
    title: 'QR Generado',
    message: 'Tu QR fue generado exitosamente, ahora podrás entrar a tu tienda escaneando el QR',
    autoClose: 3000,
  },
  STORE_QR_GENERATION_FAILED: {
    id: 'STORE_QR_GENERATION',
    loading: false,
    title: 'No se pudo generar el QR',
    message: 'Inténtalo más tarde y si el problema continúa, contáctanos.',
    autoClose: false,
    color: 'red',
  },
  STORE_QR_DOWNLOAD_SUCCESS: {
    id: 'DOWNLOAD_QR',
    loading: false,
    title: '¡La imagen se ha descargado con éxito!',
    message: 'La imagen ha sido descargada con éxito.',
    autoClose: false,
    color: 'green',
  },
  STORE_QR_DOWNLOAD_FAILED: {
    id: 'DOWNLOAD_QR',
    loading: false,
    title: 'Hubo un error al intentar descargar la imagen',
    message: 'Inténtalo más tarde y si el problema continúa, contáctanos.',
    autoClose: false,
    color: 'red',
  },
  CHANGE_STORE_AVATAR_PENDING: {
    id: 'CHANGE_STORE_AVATAR',
    loading: true,
    title: 'Cambiando el logo de tu tienda',
    message: 'Estamos procesando tu pedido.',
    autoClose: false,
    withCloseButton: false
  },
  CHANGE_STORE_AVATAR_SUCCESS: {
    id: 'CHANGE_STORE_AVATAR',
    loading: false,
    title: '¡Cambio de logo exitoso!',
    message: 'Tu tienda fue actualizada con éxito.',
    autoClose: 3000,
  },
  CHANGE_STORE_AVATAR_FAILED: {
    id: 'CHANGE_STORE_AVATAR',
    loading: false,
    title: 'Hubo un problema',
    message: 'Inténtalo más tarde y si el problema continúa, contáctanos.',
    autoClose: false,
    color: 'red',
  },
};
