export enum CacheKeyEnum {
  "USER_STORES" = "USER_STORES",
  "STORE" = "STORE",
  "PRODUCTS" = "PRODUCTS",
  "CATEGORIES" = "CATEGORIES",
  "SUBSCRIPTIONS" = "SUBSCRIPTIONS",
  "INVOICES" = "INVOICES",
  "INVITATIONS" = "INVITATIONS",
  "STORE_STAFF" = "STORE_STAFF"
}